version: "3.4"

services:
  mysqldb:
    image: moaaddocker/mediumdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root


  api:
    image: moaaddocker/mediumapi
    ports:
      - "8082:8181"
    depends_on:
      - mysqldb
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=hibernate_tutorial
      - DATABASE_PORT=3307